import { Fraunces } from 'next/font/google'
import type { Metadata } from 'next'
import Navbar from '@/components/Navbar/Navbar'
import Footer from '@/components/Footer/Footer'
import ChatBot from '@/components/ChatBot/ChatBot'
import { Providers } from './providers'
import './globals.css'

export const metadata: Metadata = {
  title: 'Mi Sitio',
  description: 'Generated by create next app',
}

const fraunces = Fraunces({
  subsets: ['latin'],
  weight: ['400', '700'],
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={fraunces.className}>
        <Providers>
          <Navbar />
          {children}
          <ChatBot />
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
