// src/app/layout.tsx
import type { Metadata } from 'next'
import Menu from './presentation/menu/menu' // Ajusta la ruta según tu estructura
import './globals.css'

export const metadata: Metadata = {
  title: 'Mi Sitio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body>
        <Menu /> {/* ← El menú aparecerá arriba de todas las páginas */}
        {children}
      </body>
    </html>
  )
}